# ------------------------------------------------------------------------------
# GENERIC EXAMPLE: SECRETS MANAGEMENT
# This example demonstrates the safest way to handle secrets in Terraform:
# Decoupling the storage of a human-entered secret from the IaC provisioning.
# 
# It assumes a human already went into the AWS Console and saved a Stripe API
# key into AWS Systems Manager (SSM) Parameter Store.
# ------------------------------------------------------------------------------

# 1. Variables (Simulating a generic environment)
variable "project" {
  description = "The project name"
  type        = string
  default     = "prasaarit"
}

variable "environment" {
  description = "The deployment environment"
  type        = string
  default     = "stg"
}

# ------------------------------------------------------------------------------
# STEP 1: Dynamically Fetch the Secret at Deployment Time
# Terraform will reach into AWS, decrypt the key, and hold it in memory.
# It MUST be marked `with_decryption = true` for SecureStrings.
# ------------------------------------------------------------------------------
data "aws_ssm_parameter" "stripe_api_key" {
  name            = "/${var.project}/${var.environment}/stripe-secret-key"
  with_decryption = true
}

# ------------------------------------------------------------------------------
# STEP 2: Use the Secret in your Infrastructure
# Here we inject the secret into a Lambda environment variable. 
# Because it was fetched via `data`, the hardcoded secret is NEVER 
# written into your `main.tf` source code files tracked by Git.
#
# WARNING: It WILL still be written to your `.terraform.tfstate` file.
# Your remote state backend (e.g., S3 bucket) MUST be tightly secured.
# ------------------------------------------------------------------------------
resource "aws_lambda_function" "payment_processor" {
  function_name = "${var.project}-${var.environment}-payment-processor"
  
  # For brevity, assuming other required fields (role, filename) are configured
  role          = "arn:aws:iam::123456789012:role/dummy-role"
  filename      = "dummy.zip"
  handler       = "index.handler"
  runtime       = "nodejs20.x"

  environment {
    variables = {
      # Injecting the secret securely
      STRIPE_SECRET_KEY = data.aws_ssm_parameter.stripe_api_key.value
      NODE_ENV          = var.environment
    }
  }

  lifecycle {
    ignore_changes = [source_code_hash, filename]
  }
}

# ------------------------------------------------------------------------------
# BONUS PATTERN: Generating Random Database Passwords
# This creates a highly secure 24-character password in-memory for RDS databases.
# ------------------------------------------------------------------------------
resource "random_password" "db_master_pass" {
  length           = 24
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

# We then immediately save this generated password to SSM Vault.
# The human never types the password anywhere.
resource "aws_ssm_parameter" "db_password_vault" {
  name        = "/${var.project}/${var.environment}/rds-master-password"
  description = "Master database password generated by Terraform"
  type        = "SecureString"
  value       = random_password.db_master_pass.result
}
