TOKEN_SIZE = 500
TEXT_OVERLAP = int(TOKEN_SIZE * 0.1)

EMBEDDING_MODEL = "text-embedding-3-small"
EMBEDING_MODEL_COST_PER_MILLION = 0.02
EMBED_BATCH_SIZE = 2048

QDRANT_COLLECTION = "documind"
SCORE_THRESHOLD = 0.45
