# live/root.hcl
#
# Root parent config — included by every unit via:
#   include "root" { path = find_in_parent_folders("root.hcl") }
#
# This file defines:
#   1. Remote state (generates backend.tf) — DRY state key per unit
#   2. Provider config (generates provider.tf) — assume_role per account
#   3. Common locals
#
# Source constant: pkg/config/config.go
#   RecommendedParentConfigName = "root.hcl"

locals {
  # Read the nearest env.hcl file up the directory tree
  # This lets each environment (prod, staging) override these values
  env_vars = read_terragrunt_config(find_in_parent_folders("env.hcl"))

  account_id = local.env_vars.locals.account_id
  aws_region = local.env_vars.locals.aws_region
  role_arn   = local.env_vars.locals.role_arn

  state_bucket      = "myorg-terraform-state-${local.account_id}"
  lock_table        = "myorg-terraform-locks"
}

# --- Generate backend.tf ---
# State key is derived from the unit's path relative to this file.
# path_relative_to_include() for live/prod/app/terragrunt.hcl → "prod/app"
# S3 key becomes: prod/app/terraform.tfstate
generate "backend" {
  path      = "backend.tf"
  if_exists = "overwrite_terragrunt"
  # ^^^^ Safe: overwrites only files Terragrunt previously generated
  # (checks for signature: "# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa")
  contents = <<EOF
terraform {
  backend "s3" {
    bucket         = "${local.state_bucket}"
    key            = "${path_relative_to_include()}/terraform.tfstate"
    region         = "${local.aws_region}"
    dynamodb_table = "${local.lock_table}"
    encrypt        = true
  }
}
EOF
}

# --- Generate provider.tf ---
# Each unit gets a provider configured to assume the correct account role.
# This is why we use generate instead of a module-level provider block:
# modules should NOT configure providers (Terraform best practice).
generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite_terragrunt"
  contents = <<EOF
provider "aws" {
  region = "${local.aws_region}"
  assume_role {
    role_arn     = "${local.role_arn}"
    session_name = "terragrunt-${path_relative_to_include()}"
  }
  default_tags {
    tags = {
      ManagedBy   = "Terragrunt"
      Environment = "${basename(dirname(path_relative_to_include()))}"
      Unit        = "${basename(path_relative_to_include())}"
    }
  }
}
EOF
}

# --- Terraform version constraint ---
# Ensures every unit enforces the same minimum Terraform version
terraform_version_constraint = ">= 1.9.0, < 2.0.0"
