# terragrunt.stack.hcl
#
# Explicit stack definition — defines a reusable, versioned collection of units.
# Source: pkg/config/stack.go
#   StackConfigFile struct has: Stacks []*Stack, Units []*Unit
#   Generated units land in: .terragrunt-stack/<path>/
#   Each unit receives a terragrunt.values.hcl with the values block contents.
#
# DefaultStackFile = "terragrunt.stack.hcl"  (config.go constant)
# StackDir = ".terragrunt-stack"             (stack.go constant)

locals {
  environment = "prod"
  region      = "ap-south-1"
}

# --- Unit blocks ---
# Each unit block references a versioned module and provides values.
# Values are written to .terragrunt-stack/<path>/terragrunt.values.hcl
# by writeValues() in stack.go.

unit "vpc" {
  source = "git::github.com/myorg/modules.git//vpc?ref=v2.1.0"
  path   = "vpc"
  values = {
    cidr_block        = "10.0.0.0/16"
    availability_zones = ["ap-south-1a", "ap-south-1b"]
    environment       = local.environment
  }
}

unit "ecs_cluster" {
  source = "git::github.com/myorg/modules.git//ecs-cluster?ref=v1.3.0"
  path   = "ecs-cluster"
  values = {
    cluster_name = "myorg-${local.environment}"
    environment  = local.environment
  }
}

unit "app" {
  source = "git::github.com/myorg/modules.git//app?ref=v2.3.1"
  path   = "app"
  values = {
    environment     = local.environment
    desired_count   = 3
    container_image = "ghcr.io/myorg/app:v1.0.0"
  }
}

# --- Stack blocks (nesting stacks within stacks) ---
# A stack block references another terragrunt.stack.hcl, enabling
# hierarchical composition of reusable infrastructure components.
# stack "monitoring" {
#   source = "git::github.com/myorg/infra-stacks.git//monitoring?ref=v1.0.0"
#   path   = "monitoring"
#   values = {
#     environment = local.environment
#   }
# }

# ===== Generated file structure =====
# .terragrunt-stack/
# ├── vpc/
# │   ├── main.tf          (from module source)
# │   ├── variables.tf
# │   └── terragrunt.values.hcl  ← auto-generated with values block above
# ├── ecs-cluster/
# │   ├── main.tf
# │   └── terragrunt.values.hcl
# └── app/
#     ├── main.tf
#     └── terragrunt.values.hcl

# terragrunt.values.hcl content example (auto-generated, do NOT edit manually):
# # Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
# container_image = "ghcr.io/myorg/app:v1.0.0"
# desired_count   = 3
# environment     = "prod"
