# Example 01 — Version Pinning

# This is the minimum version constraint block every root module should have.
# It sits in a terraform {} block, typically in main.tf or versions.tf.

terraform {
  # ~> 1.9 means: >= 1.9.0, < 2.0.0
  # Allows patch upgrades (1.9.1, 1.9.8) but rejects the next minor (1.10.0).
  # This matters because Terraform 1.10 introduced ephemeral resources — a
  # behavioural change. Without pinning, a CI runner upgrade could silently
  # change your plan semantics.
  required_version = "~> 1.9"

  required_providers {
    aws = {
      source  = "hashicorp/aws"

      # ~> 5.0 means: >= 5.0.0, < 6.0.0
      # Provider major versions can remove resources, rename arguments, or flip
      # defaults. The v4→v5 AWS provider migration disaggregated S3 bucket
      # resources — a breaking change that would silently destroy S3
      # configuration if the version constraint was left open (>= 4.0).
      version = "~> 5.0"
    }
  }
}

# -----------------------------------------------------------------------
# The .terraform.lock.hcl file (auto-generated by terraform init)
# -----------------------------------------------------------------------
#
# Terraform writes this file NEXT TO your main.tf after init.
# It records the exact provider version AND a hash of the binary.
#
# Example entry in the generated lock file:
#
#   provider "registry.terraform.io/hashicorp/aws" {
#     version     = "5.45.0"
#     constraints = "~> 5.0"
#     hashes = [
#       "h1:abc123...",
#     ]
#   }
#
# COMMIT THIS FILE. If it is missing from git:
#   - The next engineer who runs `terraform init` gets "latest 5.x"
#     at that moment, which may be 5.99.0 with breaking changes.
#   - The CI runner gets a different binary than the developer.
#
# To intentionally upgrade the provider:
#   terraform init -upgrade
#   git add .terraform.lock.hcl
#   git commit -m "chore: upgrade aws provider to 5.50"
